language: python
sudo: false
python:
- 3.4
- 3.6
- 3.5
script: tox
# Install Dependencies
install:
  - pip install -r requirements_dev.txt
  - pip install -r requirements.txt
  - pip install -U tox-travis
# Run Tests
script:
  - make test
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: cesar-rodriguez
  password:
    secure: !!binary |
      SVRNa3ZwdUVhTUljQ3FYNkhwRnhabzA1NWpIdjRUNjNrajhmc1lEczIwMUZBTVpMb1o5VXkxdnJB
      ZTM5cm5mRlFpakJUblpoV0syMFJtMXoxeTBaWkEzb0FvUHZKV1JHb3VnanYwenF3SVRnZ0ViSTR1
      djF6eklSUVhFdTFJbDlZVDA4c0pkM0gxeWVKL0xTMFIyeGIwZ09KZFN6SEo1UWhuOFo2c1BrSGJK
      QWhKbFBGSnhOWVloTmtWQVdXUnJtbnB4cFp1M2tzTDZTeWlIWFdwd2Q1V3BRS2Z4MW4vVUZkcW9u
      T0VFNlRtQUZNKzljbFN1a0UxMjdlYlA0NldHenJKUUhOV1JpL29BVExDcEh1akVnRzV5WHVuQisw
      UEw4d0Vnbm05Y2hkWFJJK1ZtYlZyR3dBUUZTSlFzdjRnOG1Jd3BaMkJrdjV2NjFySW4zanZXVzh1
      akYwV0hoY2lkWmJocG85aTI0eEdGc01oNVRyclJaNTUreUcxNlRnd2k5bkhxNWlocnZWb1dZeE9h
      MmlaVm0wSy8yK3Q2dm94cmx3MWtLVFBWVUNoWTV0aGtkK2FTcU9nSFF5UFVISVBFZ215TWxpN2Nr
      cU1nOGIvdUU1aUZPdEUxRk8rVGcraWhKN2tXYlNTdDk0OXZJUEFaNmhmbFFUcG5MT2RKU1diZnE3
      Y3J6d0ZQTVlKK0UxZlZacWVtUGRsdUhKcVJVcTlUU2RGejVtZ2hsMUorY0x6SzVJN0lneWVTdmJh
      K3BCS1JEa0k4T1V6ZXlFY29Nb1RXWGZOcUM0Q2R4bElDMStZWXBGUTBSZEs4RGR5MU80NmZTeFIy
      V2VrK3preW9nYXp2SjBKMjJIZWdtZGsvREhxZ0ZkaWpUYkRMUDBxVE9qN1hLM3VJWnpNS2FMcGs9
  true:
    python: 3.6
    repo: cesar-rodriguez/terrascan
    tags: true
